In [4]:
import pandas as pd 
import numpy as np 

df_link = pd.read_csv('/Users/takahiromatsunaga/res2023/shibuya_nw/shibuya_stanw/stanw_link.csv')
df_link_inverse = pd.read_csv('/Users/takahiromatsunaga/res2023/shibuya_nw/shibuya_stanw/stanw_link_inverse.csv')
output_file = '/Users/takahiromatsunaga/res2023/shibuya_nw/shibuya_stanw/stanw_link_post.csv'
# df_linkとdf_link_inverse

# ひとまず工事後を考えるので，工事後には消えてるノードをoかdに含んでる列を消す．
deleted_post = [16, 17, 18, 19, 20, 21, 22, 23, 30, 40, 41, 42]

# ここから，まずは
for i in range(len(df_link)):
    df_link = df_link[~df_link['o'].isin(deleted_post) & ~df_link['d'].isin(deleted_post)]

for i in range(len(df_link_inverse)):
    df_link_inverse = df_link_inverse[~df_link_inverse['o'].isin(deleted_post) & ~df_link_inverse['d'].isin(deleted_post)]

df_link = df_link.fillna(0)
df_link_inverse = df_link_inverse.fillna(0)

df_link.reset_index(drop=True, inplace=True)
df_link_inverse.reset_index(drop=True, inplace=True)

df_link.to_csv('/Users/takahiromatsunaga/res2023/shibuya_nw/shibuya_stanw/stanw_link_post.csv')
df_link_inverse.to_csv('/Users/takahiromatsunaga/res2023/shibuya_nw/shibuya_stanw/stanw_link_inverse_post.csv')
print(df_link)

    linkid     o     d  length  width  home  staire  esc  gate
0        1     1     2      25    0.0     1     0.0  0.0   0.0
1        2     2     3      25    0.0     1     0.0  0.0   0.0
2        3     3     4      25    0.0     1     0.0  0.0   0.0
3        4     4     5      25    0.0     1     0.0  0.0   0.0
4        5     5     6      25    0.0     1     0.0  0.0   0.0
5        6     6     7      25    0.0     1     0.0  0.0   0.0
6        7     8     9      25    0.0     1     0.0  0.0   0.0
7        8     9    10      25    0.0     1     0.0  0.0   0.0
8        9    10    11      25    0.0     1     0.0  0.0   0.0
9       10    11    12      25    0.0     1     0.0  0.0   0.0
10      11    12    13      25    0.0     1     0.0  0.0   0.0
11      12    13    14      25    0.0     1     0.0  0.0   0.0
12      13    14    15      25    0.0     1     0.0  0.0   0.0
13      21    24    25      20    0.0     0     0.0  0.0   1.0
14      22    25    26      25    0.0     0     0.0  0.

In [7]:
import pandas as pd 
import numpy as np 

df_link = pd.read_csv('/Users/takahiromatsunaga/res2023/shibuya_nw/shibuya_stanw/stanw_link_post.csv')
df_link_inverse = pd.read_csv('/Users/takahiromatsunaga/res2023/shibuya_nw/shibuya_stanw/stanw_link_inverse_post.csv')
output_file = '/Users/takahiromatsunaga/res2023/shibuya_nw/shibuya_stanw/stanw_alllink_post.csv'
# df_linkとdf_link_inverse

# df_linkとdf_link_inverseをconcatして'linkid'でsortしてresetindexする
df_integrated = pd.concat([df_link, df_link_inverse])

df_integrated = df_integrated.sort_values('linkid').reset_index(drop = True)

print(df_integrated)

df_integrated.to_csv(output_file)

    linkid     o     d  length  width  home  staire  esc  gate
0        1     1     2      25      0     1       0    0     0
1        2     2     1      25      0     1       0    0     0
2        3     2     3      25      0     1       0    0     0
3        4     3     2      25      0     1       0    0     0
4        5     3     4      25      0     1       0    0     0
..     ...   ...   ...     ...    ...   ...     ...  ...   ...
91      92  1527    15      20      0     0       1    0     0
92      93  1527    27      20      0     0       1    0     0
93      94    27  1527      20      0     0       1    0     0
94      95  2327    27      20      0     0       1    0     0
95      96    27  2327      20      0     0       1    0     0

[96 rows x 9 columns]


matrixdataを作る必要

In [21]:
# これは各リンクがどのリンクに接続しているかをしめすもの
import pandas as pd 
import numpy as np 
df_link = pd.read_csv('/Users/takahiromatsunaga/res2023/shibuya_nw/shibuya_stanw/stanw_alllink_post.csv')
output_file = '/Users/takahiromatsunaga/res2023/shibuya_nw/shibuya_stanw/stanw_matrix_post.csv'

array = np.zeros(2)

for k in range(len(df_link)):
    d_k = df_link.loc[k, 'd'] # link kのdノード
    print(f'link{k+1}のdノードは{d_k}')
    linkids = df_link[df_link['o'] == d_k]['linkid'].tolist() #.iloc[0]  # ??
    print(linkids)

    if not linkids: # linkidsが空の場合
        continue

    for linkid in linkids:
        c = np.array([k+1, linkid])
        print(c)
        array = np.vstack((array, c))

array = np.delete(array, 0, axis = 0)

matrix = pd.DataFrame(array, columns=['k', 'a'])

print(matrix)

matrix.to_csv(output_file)

link1のdノードは2
[2, 3, 51]
[1 2]
[1 3]
[ 1 51]
link2のdノードは1
[1]
[2 1]
link3のdノードは3
[4, 5, 67]
[3 4]
[3 5]
[ 3 67]
link4のdノードは2
[2, 3, 51]
[4 2]
[4 3]
[ 4 51]
link5のdノードは4
[6, 7, 55, 79]
[5 6]
[5 7]
[ 5 55]
[ 5 79]
link6のdノードは3
[4, 5, 67]
[6 4]
[6 5]
[ 6 67]
link7のdノードは5
[8, 9]
[7 8]
[7 9]
link8のdノードは4
[6, 7, 55, 79]
[8 6]
[8 7]
[ 8 55]
[ 8 79]
link9のdノードは6
[10, 11, 83]
[ 9 10]
[ 9 11]
[ 9 83]
link10のdノードは5
[8, 9]
[10  8]
[10  9]
link11のdノードは7
[12]
[11 12]
link12のdノードは6
[10, 11, 83]
[12 10]
[12 11]
[12 83]
link13のdノードは9
[14, 15, 71]
[13 14]
[13 15]
[13 71]
link14のdノードは8
[13]
[14 13]
link15のdノードは10
[16, 17, 59]
[15 16]
[15 17]
[15 59]
link16のdノードは9
[14, 15, 71]
[16 14]
[16 15]
[16 71]
link17のdノードは11
[18, 19, 63, 75]
[17 18]
[17 19]
[17 63]
[17 75]
link18のdノードは10
[16, 17, 59]
[18 16]
[18 17]
[18 59]
link19のdノードは12
[20, 21]
[19 20]
[19 21]
link20のdノードは11
[18, 19, 63, 75]
[20 18]
[20 19]
[20 63]
[20 75]
link21のdノードは13
[22, 23, 65]
[21 22]
[21 23]
[21 65]
link22のdノードは12
[20, 21]
[22 20]
[22 21]

In [37]:
##### 同時推定コード #####
# ver1128．ついにちゃんとした尤度関数（交差エントロピー）の定式化ができそう．それに基づいた推定コード

import pandas as pd 
import os
import datetime
import numpy as np
from datetime import timedelta 
import csv
import time
import math
from scipy.stats import norm
from scipy.optimize import minimize
import random

start_time = time.time()
print('start!')

####### reading data #######
# inputも時間間隔20secで実行
df_quater = pd.read_csv('/Users/takahiromatsunaga/res2023/bledata/ble_timegroup/20230130_08/20230130_0815_kai.csv')
search_folder = "/Users/takahiromatsunaga/res2023/bledata/ble_timegroup/20230130_08/user_stock_kai0015_end21/groups/group_2"
file_list = list(os.listdir(search_folder))

# df_linkも作り直し
df_link = pd.read_csv('/Users/takahiromatsunaga/res2023/shibuya_nw/shibuya_stanw/stanw_alllink_post.csv')
L = len(df_link)

# df_nodeは作り直し
df_node = pd.read_csv('/Users/takahiromatsunaga/res2023/shibuya_nw/shibuya_stanw/stanw_node.csv')

df_ble = pd.read_csv('/Users/takahiromatsunaga/res2023/shibuya_nw/shibuya_nw_detail/ble_nw.csv')

matrix = pd.read_csv('/Users/takahiromatsunaga/res2023/shibuya_nw/shibuya_stanw/stanw_matrix_post.csv')

###### 各linkのoとdの座標を入れておく配列 ######
oddslink_loc_array = [] 
for i in range(len(df_link)):
    linkid = df_link.loc[i, 'linkid']
    O = df_link.loc[i, 'o']
    D = df_link.loc[i, 'd']
    #print(i, O, D)
    x_o = df_node[df_node['nodeid'] == O]['x'].iloc[0]
    y_o = df_node[df_node['nodeid'] == O]['y'].iloc[0]
    z_o = df_node[df_node['nodeid'] == O]['floor'].iloc[0] 
    o_loc = np.array([x_o, y_o, z_o])
    #print(o_loc)

    x_d = df_node[df_node['nodeid'] == D]['x'].iloc[0]
    y_d = df_node[df_node['nodeid'] == D]['y'].iloc[0]
    z_d = df_node[df_node['nodeid'] == D]['floor'].iloc[0] # これでseriesではなく値として抽出できるはず
    d_loc = np.array([x_d, y_d, z_d])

    loc_tuple = (o_loc, d_loc)

    oddslink_loc_array.append(loc_tuple) # oddslink_loc_array[linkid//2][0]がlinkidのonode, [1]がdnode，[2]が中点，，，，

###### ビーコンとリンク線分の最短距離返す関数 ######
def shortest_distance_to_segment(p1, p2, x):
    p1 = np.array(p1)
    p2 = np.array(p2)
    x = np.array(x)
    
    segment = p2 - p1
    v1 = x - p1
    v2 = x - p2
    mid_point = (p1 + p2) / 2

    # 垂直ベクトルを計算
    v = v1 - np.dot(v1, segment) / np.dot(segment, segment) * segment
    
    distance = np.linalg.norm(x - mid_point)
    
    return distance

###### d_arrayの用意 ###### # 各リンク(奇数側)とbleビーコンとの（中点の）距離配列
d_array = np.zeros((len(df_link), len(df_ble)))

for i in range(len(df_link)):
    p_o = oddslink_loc_array[i][0] # o座標 # i=1の時
    p_d = oddslink_loc_array[i][1] # d座標

    for j in range(len(df_ble)):
        x_ap = df_ble.loc[j, 'x']
        y_ap = df_ble.loc[j, 'y']
        z_ap = df_ble.loc[j, 'floor']
        p_ap = np.array([x_ap, y_ap, z_ap])

        d_array[i, j] = shortest_distance_to_segment(p_o, p_d, p_ap) # ijはlink i+1, ビーコンj+1の距離

###### 混雑度dens，maxRSSI，meanRSSI，検出回数を各ビーコン各timestepごとに入れた配列（ビーコン数23*タイムステップ数） ######
### 20秒にするのでここやり直す．
dens_jt = np.zeros((23, 60), dtype = int)
max_jt = np.zeros((23, 60), dtype = int)
mean_jt = np.zeros((23, 60), dtype = int)
#count_jt = np.zeros((23, 60), dtype = int)

grouped = df_quater.groupby(['ID', 'timestep']) # listにして渡す必要がある
df_list = [group.reset_index(drop=True) for name, group in grouped]

for group in df_list:
    # beacon_idとtimestepを得る
    beacon_id = int(group.loc[0, 'ID'])
    timestep = int(group.loc[0, 'timestep'])

    # ユニークMACアドレス数，最大&平均RSSI
    unique_mac_count = group['MAC'].nunique()
    max_rssi = group['RSSI'].max()
    mean_rssi = group['RSSI'].mean()
    # countはそのタイムステップでの全検出数つまりgroupの長さそのもの
    # count = len(group)

    # numpy配列の要素はシーケンスダ
    dens_jt[beacon_id-1, timestep-1] = unique_mac_count
    max_jt[beacon_id-1, timestep-1] = max_rssi
    mean_jt[beacon_id-1, timestep-1] = mean_rssi
    # count_jt[beacon_id-1, timestep-1] = count

###### 接続行列 ###### この前にmatrix dataを作成する必要がある．
# I = np.eye(L)  # LxLの0で初期化された行列を作成．滞在をOKにするので対角成分1
# for i in range(matrix.shape[0]):
#    kn = matrix[i, 0]
#    an = matrix[i, 1]
#    k = np.where(linkid == kn)[0]  # knに対応するインデックスを取得
#    a = np.where(linkid == an)[0]  # anに対応するインデックスを取得
#    I[k, a] = 1  # 対応する位置に1を設定

####### リンク接続行列 ####### 
def Imake(link_data):
    n = len(link_data)
    I = np.eye(n)
    for i in range(n):
        D = link_data.loc[i, 'd']
        for j in range(n):
            if link_data.loc[j, 'o'] == D: 
                I[i, j] = 1
    return(I)

###### 接続行列 ###### 吸収リンクから吸収リンクへの接続は0に直す
I = Imake(df_link) 

# 最後に吸収リンク同士の接続は変なので最後のところ0にする
I[96, 96] = 0
I[97, 97] = 0
I[98, 98] = 0

###### 

###### 改札の吸収リンク
ddata = [97, 98, 99]  

D = len(ddata)

####### パラメタ初期設定 #######
xdim = 2
x0 = np.zeros(xdim)
x0[0] = -1
x0[-1] = 0.8

####### 観測方程式 ###### （観測確率．リンクkにいるとき，最大スコアのビーコンがjになる確率）
def mq(dist, distmin):     # 基本的にdistに反比例するか，それか何かの分布を与える．とりあえず試すしかないわ．
    return (distmin / dist) # これはリンクとビーコンの距離d_arrayを読み込めばOKかな

####### 観測方程式（ビーコンの評価） ######
def beacon_eval(rssi, max_rssi, freq): # 同時刻内で捕捉されたビーコンを評価．最大rssiと観測頻度による．20secも幅があるので
    return (max_rssi/rssi + freq) 

####### 観測モデル ###### # 各個人の各tiemstepに対して最もスコアの高いビーコンを決めるので出力はuserid, timestep, maxbeacon, absorption
def measuring_model(x):
    print(f'paramaterは{x}')
    qall = np.zeros(4)
    for file_name in file_list:
        if file_name.endswith('.csv'):
            base_name = file_name.split('.')[0]     # 数字部分のみ
            userid = int(base_name) # 後で1列目に入れる
                    
            file_path = os.path.join(search_folder, file_name)
            dfi = pd.read_csv(file_path) 
            nts = dfi['timestep'].nunique()                

            grouped = dfi.groupby('timestep')
            dfi_list = [group.reset_index(drop=True) for name, group in grouped]  
            qi = np.zeros(4)  # userid, timestep, maxbeacon, absorptionを後で入れる

            for t in range(nts):
                dfit = dfi_list[t]
                ts = int(dfit.loc[0, 'timestep']) # これintになってるか？は要確認

                count_tot = len(dfit) # 個人i時点tのcountの総和はdfitの長さそのもの
                        
                result_beacon = dfit.groupby('ID')
                result_beacon_list = [group.reset_index(drop=True) for name, group in result_beacon]

                ### 確認
                # print(result_beacon_list)

                # 各ビーコンのscoreを記録するためのdict
                dict = {}

                for j in range(len(result_beacon_list)): # 各ビーコンの結果を束ねたdataframe
                    dfitj = result_beacon_list[j]
                    count = len(dfitj) # そのビーコンでの検出回数
                    jid = dfitj.loc[0, 'ID']
                    rssi = dfitj['RSSI'].max() # そのビーコンでの最大観測強度

                    max_rssi = max_jt[jid-1, ts-1] # tsでのbeaconのmaxのrssi
                    freq = count / count_tot

                    # このビーコンのスコアを計算
                    jscore = beacon_eval(rssi, max_rssi, freq)
                    # print(f'user{userid}時刻{ts}のjidつまりビーコンのidは{jid}，そのスコアは{jscore}')

                    # dictにjidとjscoreを入れる
                    # dict.update(jid = jscore)
                    dict[jid] = jscore

                # dictに全部入っているので比較
                max_beacon = max(dict, key = dict.get) # score maxのビーコン

                # 個人i時刻tの結果（最もスコアの高かったビーコン）．absorptionの列はとりあえず0のまま残しておく
                qit = np.array([userid, ts, max_beacon, 0])
                qi = np.vstack((qi, qit))
            
            # qiの冒頭の0の行を削除
            qi = np.delete(qi, 0, axis = 0)

            # ここまでで終了したので，qiの最後の行のmaxbeaconの値を取得しそれを最後の列に入れる
            abs = qi[-1, 2] # これで最後の行のmaxbeaconの列（0から数えて2列目）
            # qiの最後の列の値を全てabsにする
            qi[:, -1] = abs

            # 全個人に対してvstackしていってqallを作る
            qall = np.vstack((qall, qi))

    # 冒頭の0の行を削除
    qall = np.delete(qall, 0, axis = 0)
    return qall 

print(measuring_model(0))



start!
paramaterは0
[[ 78.  41.   3.  21.]
 [ 78.  42.   4.  21.]
 [ 78.  43.   5.  21.]
 ...
 [139.   3.  20.  21.]
 [139.   4.  20.  21.]
 [139.   5.  21.  21.]]


In [39]:
import numpy as np

# 例としての dist_list
dist_list = np.array([5, 3, 8, 1, 1, 3, 1, 8, 2])

# dist_list から最小値のインデックスを取得
min_indices = np.argwhere(dist_list == np.min(dist_list)).flatten()+1

print("最小値のインデックス:")
print(min_indices)


最小値のインデックス:
[4 5 7]


In [26]:
##### 同時推定コード #####
# ver1128．ついにちゃんとした尤度関数（交差エントロピー）の定式化ができそう．それに基づいた推定コード

import pandas as pd 
import os
import datetime
import numpy as np
from datetime import timedelta 
import csv
import time
import math
from scipy.stats import norm
from scipy.optimize import minimize
import random

start_time = time.time()
print('start!')

####### reading data #######
# inputも時間間隔20secで実行
df_quater = pd.read_csv('/Users/takahiromatsunaga/res2023/bledata/ble_timegroup/20230130_08/20230130_0845_20sec.csv')
search_folder = "/Users/takahiromatsunaga/res2023/bledata/ble_timegroup/20230130_08/20230130_0845_20sec_end162021_under10step"
file_list = list(os.listdir(search_folder))

# df_linkも作り直し
df_link = pd.read_csv('/Users/takahiromatsunaga/res2023/shibuya_nw/shibuya_stanw/stanw_alllink_post.csv')
L = len(df_link)

# df_nodeは作り直し
df_node = pd.read_csv('/Users/takahiromatsunaga/res2023/shibuya_nw/shibuya_stanw/stanw_node.csv')

df_ble = pd.read_csv('/Users/takahiromatsunaga/res2023/shibuya_nw/shibuya_nw_detail/ble_nw.csv')

matrix = pd.read_csv('/Users/takahiromatsunaga/res2023/shibuya_nw/shibuya_stanw/stanw_matrix_post.csv')

###### 各linkのoとdの座標を入れておく配列 ######
oddslink_loc_array = [] 
for i in range(len(df_link)):
    linkid = df_link.loc[i, 'linkid']
    O = df_link.loc[i, 'o']
    D = df_link.loc[i, 'd']

    x_o = df_node[df_node['nodeid'] == O]['x'].iloc[0]
    y_o = df_node[df_node['nodeid'] == O]['y'].iloc[0]
    z_o = df_node[df_node['nodeid'] == O]['floor'].iloc[0] 
    o_loc = np.array([x_o, y_o, z_o])

    x_d = df_node[df_node['nodeid'] == D]['x'].iloc[0]
    y_d = df_node[df_node['nodeid'] == D]['y'].iloc[0]
    z_d = df_node[df_node['nodeid'] == D]['floor'].iloc[0] # これでseriesではなく値として抽出できるはず
    d_loc = np.array([x_d, y_d, z_d])

    loc_tuple = (o_loc, d_loc)

    oddslink_loc_array.append(loc_tuple) # oddslink_loc_array[linkid//2][0]がlinkidのonode, [1]がdnode，[2]が中点，，，，

###### ビーコンとリンク線分の中点間距離を返す関数 ######
def shortest_distance_to_segment(p1, p2, x):
    p1 = np.array(p1)
    p2 = np.array(p2)
    x = np.array(x)
    
    segment = p2 - p1
    v1 = x - p1
    v2 = x - p2
    mid_point = (p1 + p2) / 2

    # 垂直ベクトルを計算
    v = v1 - np.dot(v1, segment) / np.dot(segment, segment) * segment
    
    distance = np.linalg.norm(x - mid_point)
    
    return distance

###### d_arrayの用意 ###### # 各リンク(の中点）とbleビーコンとの距離配列
d_array = np.zeros((len(df_link), len(df_ble)))

for i in range(len(df_link)):
    p_o = oddslink_loc_array[i][0] # o座標 # i=1の時
    p_d = oddslink_loc_array[i][1] # d座標

    for j in range(len(df_ble)):
        x_ap = df_ble.loc[j, 'x']
        y_ap = df_ble.loc[j, 'y']
        z_ap = df_ble.loc[j, 'floor']
        p_ap = np.array([x_ap, y_ap, z_ap])

        d_array[i, j] = shortest_distance_to_segment(p_o, p_d, p_ap) # ijはlink i+1, ビーコンj+1の距離

###### 混雑度dens，maxRSSI，meanRSSI，検出回数を各ビーコン各timestepごとに入れた配列（ビーコン数23*タイムステップ数） ######
### 20秒にするのでここやり直す．
dens_jt = np.zeros((23, 45), dtype = int)
max_jt = np.zeros((23, 45), dtype = int)
mean_jt = np.zeros((23, 45), dtype = int)
#count_jt = np.zeros((23, 45), dtype = int)

grouped = df_quater.groupby(['ID', 'timestep']) # listにして渡す必要がある
df_list = [group.reset_index(drop=True) for name, group in grouped]

for group in df_list:
    # beacon_idとtimestepを得る
    beacon_id = int(group.loc[0, 'ID'])
    timestep = int(group.loc[0, 'timestep'])

    # ユニークMACアドレス数，最大&平均RSSI
    unique_mac_count = group['MAC'].nunique()
    max_rssi = group['RSSI'].max()
    mean_rssi = group['RSSI'].mean()
    # countはそのタイムステップでの全検出数つまりgroupの長さそのもの
    #count = len(group)

    # numpy配列の要素はシーケンスダ
    dens_jt[beacon_id-1, timestep-1] = unique_mac_count
    max_jt[beacon_id-1, timestep-1] = max_rssi
    mean_jt[beacon_id-1, timestep-1] = mean_rssi
    #count_jt[beacon_id-1, timestep-1] = count

###### 接続行列 ###### この前にmatrix dataを作成する必要がある．
#I = np.eye(L)  # LxLの0で初期化された行列を作成．滞在をOKにするので対角成分1
#for i in range(matrix.shape[0]):
#    kn = matrix[i, 0]
#    an = matrix[i, 1]
#    k = np.where(linkid == kn)[0]  # knに対応するインデックスを取得
#    a = np.where(linkid == an)[0]  # anに対応するインデックスを取得
#    I[k, a] = 1  # 対応する位置に1を設定

####### リンク接続行列 ####### 
def Imake(link_data):
    n = len(link_data)
    I = np.eye(n)
    for i in range(n):
        D = link_data.loc[i, 'd']
        for j in range(n):
            if link_data.loc[j, 'o'] == D: 
                I[i, j] = 1
    return(I)

###### 接続行列 ###### 吸収リンクから吸収リンクへの接続は0に直す
I = Imake(df_link) 

# 最後に吸収リンク同士および階段リンク同士の接続は変なので最後のところ0にする
for i in range(51, 94):
    I[i-1, i-1] = 0

for i in range(51, 88, 4):
    # 階段のリンクは，奇数の階段はi+2にしか接続せず，i+1には接続しない．偶数の階段は
    I[i-1, i] = 0
    I[i-1, i+1] = 1
    I[i, i-1] = 0
    I[i+1, i+2] = 0
    I[i+2, i+1] = 0
    I[i+2, i] = 1

###### 改札の吸収リンク
ddata = [91, 92, 93]
# ddata = [33, 35, 49]

D = len(ddata)

####### パラメタ初期設定 #######
xdim = 2
x0 = np.zeros(xdim)

####### 観測方程式 ###### （観測確率．リンクkにいるとき，最大スコアのビーコンがjになる確率）
def mq(dist, distmin):     # 基本的にdistに反比例するか，それか何かの分布を与える．とりあえず試すしかないわ．
    return (distmin / dist) # これはリンクとビーコンの距離d_arrayを読み込めばOKかな

####### 観測方程式（ビーコンの評価） ######
def beacon_eval(rssi, max_rssi, freq): # 同時刻内で捕捉されたビーコンを評価．最大rssiと観測頻度による．20secも幅があるので
    return (max_rssi/rssi + freq) 

####### 観測モデル ###### # 各個人の各tiemstepに対して最もスコアの高いビーコンを決めるので出力はuserid, timestep, maxbeacon, absorption
def measuring_model(x):
    print(f'paramaterは{x}')
    qall = np.zeros(4)
    for file_name in file_list:
        if file_name.endswith('.csv'):
            base_name = file_name.split('.')[0]     # 数字部分のみ
            userid = int(base_name) # 後で1列目に入れる
                    
            file_path = os.path.join(search_folder, file_name)
            dfi = pd.read_csv(file_path) 
            nts = dfi['timestep'].nunique()                

            grouped = dfi.groupby('timestep')
            dfi_list = [group.reset_index(drop=True) for name, group in grouped]  
            qi = np.zeros(4)  # userid, timestep, maxbeacon, absorptionを後で入れる

            for t in range(nts):
                dfit = dfi_list[t]
                ts = int(dfit.loc[0, 'timestep']) # これintになってるか？は要確認

                count_tot = len(dfit) # 個人i時点tのcountの総和はdfitの長さそのもの
                        
                result_beacon = dfit.groupby('ID')
                result_beacon_list = [group.reset_index(drop=True) for name, group in result_beacon]

                ### 確認
                # print(result_beacon_list)

                # 各ビーコンのscoreを記録するためのdict
                dict = {}

                for j in range(len(result_beacon_list)): # 各ビーコンの結果を束ねたdataframe
                    dfitj = result_beacon_list[j]
                    count = len(dfitj) # そのビーコンでの検出回数
                    jid = dfitj.loc[0, 'ID']
                    rssi = dfitj['RSSI'].max() # そのビーコンでの最大観測強度

                    max_rssi = max_jt[jid-1, ts-1] # tsでのbeaconのmaxのrssi
                    freq = count / count_tot

                    # このビーコンのスコアを計算
                    jscore = beacon_eval(rssi, max_rssi, freq)

                    # dictにjidとjscoreを入れる
                    # dict.update(jid = jscore)
                    dict[jid] = jscore

                # dictに全部入っているので比較
                max_beacon = max(dict, key = dict.get) # score maxのビーコン

                # 個人i時刻tの結果（最もスコアの高かったビーコン）．absorptionの列はとりあえず0のまま残しておく
                qit = np.array([userid, ts, max_beacon, 0])
                qi = np.vstack((qi, qit))
            
            # qiの冒頭の0の行を削除
            qi = np.delete(qi, 0, axis = 0)

            # ここまでで終了したので，qiの最後の行のmaxbeaconの値を取得しそれを最後の列に入れる
            abs = qi[-1, 2] # これで最後の行のmaxbeaconの列（0から数えて2列目）
            # qiの最後の列の値を全てabsにする
            qi[:, -1] = abs

            # 全個人に対してvstackしていってqallを作る
            qall = np.vstack((qall, qi))

    # 冒頭の0の行を削除
    qall = np.delete(qall, 0, axis = 0)
    return qall 

###### 経路選択モデル ####### 
###### 初期設定 ######
V0 = np.full((L, D), -1) # exp(0)=1よりexp(-1)は小さくなるから?
z0 = np.exp(V0)

###### TSを設定しないといけない ###### #### 一斉に発生すると考えて良さそう→とりあえず時間構造化しないで解く
#TS = 10

V = V0
z = z0
# beta = x0[-1] # dRLなのでbeta推定．xの最後の要素をbetaとする
# beta = 0.99 # dRLなのでbeta推定．xの最後の要素をbetaとする

###### 効用関数 ######
def linkv(x): 
    vinst = np.exp(df_link['length']/100 * x[0]) 
    #+ df_link_integrated['staire'] * x[1]) # + df_link_integrated['staire_with_esc'] * x[3])
    return vinst # 出力形式はseries

###### 即時効用行列 ######
def Mset(x): 
    cost = linkv(x)
    cost = pd.concat([cost]*L, axis=1)
    cost = cost.T
    cost_numpy = cost.values # DataFrameをNumPy配列に変換
    return cost_numpy

###### 価値関数 ###### # 時間構造化するなら変わってくるが，，，
def newV(x):
    V = np.zeros((L, D))
    z = np.exp(V)
    
    for d in range(D): 
        d_linkid = ddata[d]
        
        d_index = df_link[df_link['linkid'] == d_linkid].index 
        z[d_index, d] = 1                   # 目的地がdの時，dでの期待効用Vd(d)=0から
        M = np.zeros((L, L))
        B = np.zeros((L, 1))
        B[d_index, 0] = 1

        # print(f'今dは{d_linkid}でzは{z}，Bは{B}')

        # Mをdごとに更新？
        for k in range(L): 
            for a in range(L): 
                Ika = I[k, a] 
                if Ika == 1:                # 接続してなければ無関係（0のまま）
                    if a == d_index: 
                        M[k, a] = 1         # 吸収リンクの即時効用はexp(0)=1
                    else:
                        M[k, a] = Mset(x)[k, a]
        dL = 100
        zd = z[:, d].reshape(L, 1) 

        # z求解
        count = 0
        while dL >= 0.01: 
            zdd = zd.copy()
            zd = M @ (zdd ** x[-1]) + B 
            # dL = np.sum(np.abs(zdd - zd)) 
            print(f'{count}回目でzは{zd}')
            dL = np.linalg.norm(zdd - zd, axis=0) 
            count += 1

        # z更新
        z[:, d] = zd[:, 0] 
        zd = np.where(zd == 0, 1, zd)  
        one_dim_array = np.log(zd).ravel()   # 1次元配列に
        V[:, d] = one_dim_array 

    return z

###### 対数尤度関数 ###### 
def loglikelihood(x):
    LL = 0

    # ここで観測モデルに入れる
    print(f'パラメタ{x}で観測モデルを回します')
    qall = measuring_model(x)
    # print(qall)

    condition = np.logical_or.reduce((qall[:, -1] == 16, qall[:, -1] == 20, qall[:, -1] == 21))

    # 条件に合致しない行のインデックスを取得します
    indices_to_keep = np.where(condition)[0]

    # 条件に合致しない行のみを抽出します
    filtered_qall = qall[indices_to_keep]

    # numpyのままではグルーピング不可なのでqallをdataframeにし，列カラムをつける
    mres = pd.DataFrame(filtered_qall, columns=['userid', 'timestep', 'maxbeacon', 'absorption']) # + [i for i in range(1, len(df_link_odds)*2+1)])

    # 観測結果をdで分割
    grouped = mres.groupby('absorption')
    df_list = [group for name, group in grouped]
    df_list = [data.reset_index(drop=True) for data in df_list]    
    # print(df_list)
    # loglikelihood内で価値関数更新
    Z = newV(x)
    print(Z)
    # 目的地dごとに計算
    for d in range(D):
        d_linkid = ddata[d] 
        d_index = df_link[df_link['linkid'] == d_linkid].index
        d_index = d_index.tolist()
        d_index = d_index[0] 

        # 価値関数
        z = Z[:, d].reshape(L, 1) # 価値関数は固定じゃなくてloglikelihood内で逐次更新→直したらループが終わらないことは無くなった
        z = z ** x[-1]
        ZD = np.tile(z, (1, L))
        ZD = ZD.T

        #print(z)

        # Mをdごとに更新（dループの外で問題はなさそう）
        M = np.zeros((L, L))
        for k in range(L): 
            for a in range(L): 
                Ika = I[k, a] 
                if Ika == 1:                            # 接続してなければ無関係（0のまま）
                    if a == d_index: 
                        M[k, a] = 1                     # 吸収リンクの即時効用はexp(0)=1（接続してたら）
                    else:
                        M[k, a] = Mset(x)[k, a]
        print(M)

        # 選択確率
        Mz = (M @ z != 0) * (M @ z) + (M @ z == 0)  
        MZ = np.tile(Mz, (1, L))  
        p = (M * ZD) / MZ

        print(p)

        # dを目的地とするユーザのデータを読み込む
        df = df_list[d]
        # print(df) # おかしくなってる．

        grouped2 = df.groupby('userid')
        df_list2 = [group for name, group in grouped2] # df_list2の長さが目的地をdとするuserの数に等しい
        df_list2 = [data2.reset_index(drop=True) for data2 in df_list2]
        count = 0

        for i in range(len(df_list2)): # 各userについてみて回る
            # print(f'{len(df_list2)}のなかで今{i}番目') # len(df_list2)が1になっている
            dfi = df_list2[i] # 各自の結果（userid, timestep, maxbeacon, absorption）
            userid = dfi.loc[0, 'userid']
            LLi = 0 # 個人iの尤度和
            at_cand_list = [] # 初期化
            # 各時刻ごとにmaxbeaconを参照．dfiの長さが滞在timestep数と同じになる
            for t in range(0, len(dfi)):                     # timestep1と最後とそれ以外で処理変わる
                max_beacon = int(dfi.loc[t, 'maxbeacon']) # intじゃないと後でスライスできないらしいわ
                ts = dfi.loc[t, 'timestep']
                # print(f'user{userid}時刻{ts}でmaxbeaconは{max_beacon}')
                at_1_list = at_cand_list # at_1_listは膨れていくが，しょうがない？結局選択されなそうなリンクは尤度小さくなるだけなので，，
                at_cand_list = [] # 空にしておく

                if t == 0: # 初期のリンクは重要．max_beaconから，近いやつを候補にするが，幾つにするかで比較するか？とりあえず一個に決めるかー最短の．
                    # 次のmaxbeacon 
                    next_max_beacon = int(dfi.loc[1, 'maxbeacon'])
                    # next_max_beaconの座標
                    x_nb = df_ble.loc[next_max_beacon-1, 'x']
                    y_nb = df_ble.loc[next_max_beacon-1, 'y']
                    z_nb = df_ble.loc[next_max_beacon-1, 'floor']
                    loc_nb = np.array([x_nb, y_nb, z_nb])

                    # 候補リンク（場所は一意に決まって，シンプルに向きの関係で二つ候補ができる）
                    dist_list = d_array[:, max_beacon-1]
                    # print(dist_list)
                    dist_min_links = np.argwhere(dist_list == np.min(dist_list)).flatten()+1
                    # print(f'user{userid}時刻{ts}つまり最初のリンクの候補は{dist_min_links}')
                    dict2 = {}
                    for dist_min_link in dist_min_links:
                        dist_min_link_d = df_link[df_link['linkid'] == dist_min_link]['d'].iloc[0] # 注目リンクのdノード（のid）
                        # print(dist_min_link_d) # 値が二つ出ているのでエラーが出ている→ilocつけたら解消

                        x_mld = df_node[df_node['nodeid'] == dist_min_link_d]['x'] # そのdノードの各座標
                        y_mld = df_node[df_node['nodeid'] == dist_min_link_d]['y']
                        z_mld = df_node[df_node['nodeid'] == dist_min_link_d]['floor']
                        loc_minlinkd = np.array([x_mld, y_mld, z_mld])
                        
                        distance = np.linalg.norm(loc_minlinkd - loc_nb)
                        # print(dist_min_link, distance)
                        # linkidと次のスコア最大ビーコンとの距離を計算
                        dict2[dist_min_link] = distance
                    
                    # loc_minlinkdとloc_nbの距離が近い方を採用し，a0とする 
                    a0 = min(dict2, key = dict2.get) 
                    at_cand_list = [a0] # 初期は選択確率とかない．はず．一個に決めるなら
                    # print(f'user{userid}時刻{ts}つまり最初のリンクは{at_cand_list}．ちなみにこの時maxbeaconは{max_beacon}で次のbeaconは{next_max_beacon}')

                if t >= 1 and t <= (len(dfi)-2):            
                    for at_1 in at_1_list: # at_1に接続しているリンクを全部とる
                        a_row = I[at_1-1, :]
                        at_cand = np.where(a_row == 1)[0]+1 # np.whereを用いるidなので，+1をする．これlistのはず
                        at_cand_list.extend(list(set(at_cand) - set(at_cand_list))) # 重複なし．これが全atの候補
                    
                    # 各候補リンクに対してp(j|k)(pmat)を算出（これが観測確率になる）．kの候補がいっぱいあるので，まず全てのkに対して処理を行う
                    for at in at_cand_list:
                        dist = d_array[at-1, max_beacon-1]                                     
                        min_dist = d_array[:, max_beacon-1].min() # max_beaconに一番近いリンクとの距離
                        pmat = mq(dist, min_dist) # これは観測方程式，max_beaconと距離が近いリンクほど観測確率が大きくなるという単純な理屈
                        
                        # ここでもっとat_1を絞る．at_1_listに入っていてかつatと接続する→atの列が1である行のindex
                        at_col = I[:, at-1]
                        at_connected = np.where(at_col == 1)[0]+1 # np.whereを用いるidなので，+1をする．これlistのはず
                        # at_cand_list.extend(list(set(at_) - set(at_cand_list))) # 重複なし．これが全atの候補
                        common_list = [link for link in at_1_list if link in at_connected] # つまり

                        for at_1 in common_list:
                            # print(f'今見てるんはuser{userid}時刻{ts}max_beacon{max_beacon}，{at_1}から{at}への遷移')
                            at_prime_list = []
                            # 分子
                            # print(pmat, p[at_1-1, at-1])
                            nume = pmat * p[at_1-1, at-1]

                            # deno計算．at_1に接続しているリンクたち．
                            at_1_row = I[at_1-1, :]
                            at_prime_list = np.where(at_1_row == 1)[0]+1 # これリストのはず
                            # print(f'{at_1}に繋がっているリンクたち{at_prime_list}')
                            # at_prime_list.extend(list(set(at_prime) - set(at_prime_list))) # 重複するリスクないはずだが．

                            # 分母
                            deno = 0
                            for at_prime in at_prime_list:
                                # print(f'今のat_primeは{at_prime}')
                                dist = d_array[at_prime-1, max_beacon-1] # リンクの中点の方がいいかな→多分ね # ここもmax_beaconに対して実施（時刻tに紐づいている）
                                pmat_prime = mq(dist, min_dist)
                                deno += pmat_prime * p[at_1-1, at_prime-1]
                            if deno == 0:
                                continue
                            # print(f'{at_1}から{at}への遷移の時のdenoは{deno}')
                            delta = nume / deno # これがクロネッカーのデルタ

                            # 求めたら，これを元にLLitを決める．logzero回避
                            pp = (p[at_1-1, at-1] == 0) + ((p[at_1-1, at-1] != 0) * p[at_1-1, at-1])
                            LLi += delta * np.log(pp) # p=1になることはない，接続するのが一つでも滞在するという選択肢もあるので（のはず）
                            # print(f'↑の時，デルタ{nume}/{deno}={delta}，選択確率{pp}')
                                
                if t == (len(dfi) - 1):
                    # ここもatを一つに決める．最後のビーコンに応じたリンクをatに決め，(吸収リンクではなく最後のリンク→ではないポイか)
                    # print(max_beacon)
                    aT = None
                    if max_beacon == 16:
                        aT = 49 # 93
                    if max_beacon == 20:
                        aT = 33 # 91
                    if max_beacon == 21:
                        aT = 35 # 92
                    # print(aT)
                    if aT is not None:
                        dist = d_array[aT-1, max_beacon-1]
                        min_dist = d_array[:, max_beacon-1].min() # max_beaconに一番近いリンクとの距離
                        pmat = mq(dist, min_dist) # これは観測方程式，max_beaconと距離が近いリンクほど観測確率が大きくなるという単純な理屈
                        # print(f'最後のリンクは{aT}')
                        for at_1 in at_1_list:
                            at_prime_list = []
                            # 分子
                            nume = pmat * p[at_1-1, aT-1]
                            if nume == 0:
                                continue

                            # deno計算．今みているformer_link at-1に接続している全てのlinkに対して上記の計算を行う
                            # at_1に接続しているリンクたち．
                            at_1_row = I[at_1-1, :]
                            at_prime_list = np.where(at_1_row == 1)[0]+1
                            # at_prime_list.extend(list(set(at_prime) - set(at_prime_list)))

                            # 分母
                            deno = 0
                            for at_prime in at_prime_list:
                                dist_prime = d_array[at_prime-1, max_beacon-1] # リンクの中点の方がいいかな→多分ね # ここもmax_beaconに対して実施（時刻tに紐づいている）
                                pmat_prime = mq(dist_prime, min_dist) # min_distはt内で一定（t内でmaxbeaconが一定に決まるので）
                                deno += pmat_prime * p[at_1-1, at_prime-1]

                            if deno == 0:
                                    continue
                            
                            delta = nume / deno # これがクロネッカーのデルタ

                            # 求めたら，これを元にLLitを決める．logzero回避
                            pp = (p[at_1-1, aT-1] == 0) + ((p[at_1-1, aT-1] != 0) * p[at_1-1, aT-1])
                            LLi += delta * np.log(pp) # p=1になることはない，接続するのが一つでも滞在するという選択肢もあるので（のはず）
                            # print(f'user{userid}時刻{ts}つまり最後のmaxビーコンのidは{max_beacon}，リンクは{aT}デルタは{nume}/{deno}で{delta}，pmatは{pmat}，経路選択確率は{pp}')   
            LL += LLi # 個人に対して和をとる
            count += 1

        print(f'パラメタ{x}のもとでLLが回り，計算したuserは{count}人でLL={LL}') # LLは負のはず
    
    return -LL

x1 = np.array((-10,0.6))
print(loglikelihood(x1))

start!
パラメタ[-10.    0.6]で観測モデルを回します
paramaterは[-10.    0.6]
0回目でzは[[0.38159028]
 [0.16417   ]
 [0.38159028]
 [0.38159028]
 [0.51692556]
 [0.38159028]
 [0.246255  ]
 [0.51692556]
 [0.38159028]
 [0.246255  ]
 [0.16417   ]
 [0.38159028]
 [0.38159028]
 [0.16417   ]
 [0.38159028]
 [0.38159028]
 [0.38159028]
 [0.38159028]
 [0.246255  ]
 [0.38159028]
 [0.246255  ]
 [0.246255  ]
 [0.38159028]
 [0.246255  ]
 [0.29950528]
 [0.38159028]
 [0.35275557]
 [0.54134113]
 [0.60472044]
 [0.29950528]
 [0.43484056]
 [0.60472044]
 [1.44626032]
 [0.7457656 ]
 [1.27067057]
 [0.48809085]
 [0.46367528]
 [0.29950528]
 [0.46367528]
 [0.29950528]
 [0.34929235]
 [0.46367528]
 [0.27067057]
 [0.40254263]
 [0.09957414]
 [0.31699442]
 [0.51692556]
 [0.29950528]
 [1.16417   ]
 [0.51692556]
 [0.13533528]
 [0.16417   ]
 [0.29950528]
 [0.13533528]
 [0.13533528]
 [0.29950528]
 [0.29950528]
 [0.13533528]
 [0.13533528]
 [0.16417   ]
 [0.082085  ]
 [0.13533528]
 [0.13533528]
 [0.16417   ]
 [0.246255  ]
 [0.13533528]
 [0.135335

In [47]:
import numpy as np

# 例として二次元配列を作成します
array = np.array([
    [1, 2, 16],
    [3, 4, 22],  # これは削除される
    [5, 6, 20],
    [7, 8, 21],
    [9, 10, 25]  # これも削除される
])

# 最後の列の値が16, 20, 21のいずれかに当てはまる条件を作成します
condition = np.logical_or.reduce((array[:, -1] == 16, array[:, -1] == 20, array[:, -1] == 21))

# 条件に合致しない行のインデックスを取得します
indices_to_keep = np.where(condition)[0]

# 条件に合致しない行のみを抽出します
filtered_array = array[indices_to_keep]

print(filtered_array)


[[ 1  2 16]
 [ 5  6 20]
 [ 7  8 21]]


In [47]:
##### 同時推定コード #####
# ver1128．ついにちゃんとした尤度関数（交差エントロピー）の定式化ができそう．それに基づいた推定コード

import pandas as pd 
import os
import datetime
import numpy as np
from datetime import timedelta 
import csv
import time
import math
from scipy.stats import norm
from scipy.optimize import minimize
import random

start_time = time.time()
print('start!')

####### reading data #######
# inputも時間間隔20secで実行
df_quater = pd.read_csv('/Users/takahiromatsunaga/res2023/bledata/ble_timegroup/20230130_08/20230130_0845_20sec.csv')
search_folder = "/Users/takahiromatsunaga/res2023/bledata/ble_timegroup/20230130_08/20230130_0845_20sec_end162021"
file_list = list(os.listdir(search_folder))

# df_linkも作り直し
df_link = pd.read_csv('/Users/takahiromatsunaga/res2023/shibuya_nw/shibuya_stanw/stanw_link_post.csv')
L = len(df_link)

# df_nodeは作り直し
df_node = pd.read_csv('/Users/takahiromatsunaga/res2023/shibuya_nw/shibuya_stanw/stanw_node.csv')

df_ble = pd.read_csv('/Users/takahiromatsunaga/res2023/shibuya_nw/shibuya_nw_detail/ble_nw.csv')

# matrix = pd.read_csv('/Users/takahiromatsunaga/res2023/shibuya_nw/shibuya_stanw/stanw_matrix_post.csv')


###### 各linkのoとdの座標を入れておく配列 ###### # 線分とビーコンの距離に関しての情報は向きがあってもなくても変わらない
oddslink_loc_array = [] 
for i in range(len(df_link)):
    linkid = df_link.loc[i, 'linkid']
    O = df_link.loc[i, 'o']
    D = df_link.loc[i, 'd']

    x_o = df_node[df_node['nodeid'] == O]['x'].iloc[0]
    y_o = df_node[df_node['nodeid'] == O]['y'].iloc[0]
    z_o = df_node[df_node['nodeid'] == O]['floor'].iloc[0] 
    o_loc = np.array([x_o, y_o, z_o])

    x_d = df_node[df_node['nodeid'] == D]['x'].iloc[0]
    y_d = df_node[df_node['nodeid'] == D]['y'].iloc[0]
    z_d = df_node[df_node['nodeid'] == D]['floor'].iloc[0] # これでseriesではなく値として抽出できるはず
    d_loc = np.array([x_d, y_d, z_d])

    loc_tuple = (o_loc, d_loc)

    oddslink_loc_array.append(loc_tuple) # oddslink_loc_array[linkid//2][0]がlinkidのonode, [1]がdnode，[2]が中点，，，，

###### ビーコンとリンク線分の中点間距離を返す関数 ######
def shortest_distance_to_segment(p1, p2, x):
    p1 = np.array(p1)
    p2 = np.array(p2)
    x = np.array(x)
    
    segment = p2 - p1
    v1 = x - p1
    v2 = x - p2
    mid_point = (p1 + p2) / 2

    # 垂直ベクトルを計算
    v = v1 - np.dot(v1, segment) / np.dot(segment, segment) * segment
    distance = np.linalg.norm(x - mid_point)
    
    return distance

###### d_arrayの用意 ###### # 各リンク(の中点）とbleビーコンとの距離配列
d_array = np.zeros((len(df_link), len(df_ble)))

for i in range(len(df_link)):
    p_o = oddslink_loc_array[i][0] # o座標 # i=1の時
    p_d = oddslink_loc_array[i][1] # d座標

    for j in range(len(df_ble)):
        x_ap = df_ble.loc[j, 'x']
        y_ap = df_ble.loc[j, 'y']
        z_ap = df_ble.loc[j, 'floor']
        p_ap = np.array([x_ap, y_ap, z_ap])

        d_array[i, j] = shortest_distance_to_segment(p_o, p_d, p_ap) # ijはlink i+1, ビーコンj+1の距離

###### 混雑度dens，maxRSSI，meanRSSI，検出回数を各ビーコン各timestepごとに入れた配列（ビーコン数23*タイムステップ数） ######
### 20秒にするのでここやり直す．
dens_jt = np.zeros((23, 45), dtype = int)
max_jt = np.zeros((23, 45), dtype = int)
mean_jt = np.zeros((23, 45), dtype = int)
#count_jt = np.zeros((23, 45), dtype = int)

grouped = df_quater.groupby(['ID', 'timestep']) # listにして渡す必要がある
df_list = [group.reset_index(drop=True) for name, group in grouped]

for group in df_list:
    # beacon_idとtimestepを得る
    beacon_id = int(group.loc[0, 'ID'])
    timestep = int(group.loc[0, 'timestep'])

    # ユニークMACアドレス数，最大&平均RSSI
    unique_mac_count = group['MAC'].nunique()
    max_rssi = group['RSSI'].max()
    mean_rssi = group['RSSI'].mean()
    # countはそのタイムステップでの全検出数つまりgroupの長さそのもの
    #count = len(group)

    # numpy配列の要素はシーケンスダ
    dens_jt[beacon_id-1, timestep-1] = unique_mac_count
    max_jt[beacon_id-1, timestep-1] = max_rssi
    mean_jt[beacon_id-1, timestep-1] = mean_rssi
    #count_jt[beacon_id-1, timestep-1] = count

####### リンク接続行列（無向） ####### 
def I_nod(link_data): 
    n = len(link_data)
    I = np.eye(n) # 滞在リンク（吸収リンクにもつけて良い）
    for i in range(n):
        O = link_data.loc[i, 'o'] # 当該linkのOnode
        D = link_data.loc[i, 'd'] # 当該linkのDnode
        for j in range(n): # リンクiのOorDをOないしDとしているリンクjとは接続
            if ((link_data.loc[j, 'o'] == O) or (link_data.loc[j, 'o'] == D)) or (link_data.loc[j, 'd'] == O) or (link_data.loc[j, 'd'] == D): 
                I[i, j] = 1
    return(I)

I = I_nod(df_link)

###### 階段リンクについて別途処理 ###### # i = 26~44
for i in range(26, 45, 2):
    # 階段には滞在リンク入れない．向きは考えないので面倒なことは考えない
    I[i-1, i-1] = 0
    I[i, i] = 0

###### 吸収リンクからは吸収リンクにしか接続しない
for i in range(46, 49):
    I[i-1, :] = 0 # 他には繋がらない
    # I[i-1, i-1] = 1 # 自分自身にはつながる

###### 改札の吸収リンク
# ddata = [91, 92, 93]
# ddata = [33, 35, 49]
ddata = [46, 47, 48]

D = len(ddata)

####### パラメタ初期設定 #######
xdim = 2
x0 = np.zeros(xdim)
x0[0] = -1
x0[-1] = 0.8

####### 観測方程式 ###### （観測確率．リンクkにいるとき，最大スコアのビーコンがjになる確率）
def mq(dist, distmin):     # 基本的にdistに反比例するか，それか何かの分布を与える．とりあえず試すしかないわ．
    return (distmin / dist) # これはリンクとビーコンの距離d_arrayを読み込めばOKかな

####### 観測方程式（ビーコンの評価） ######
def beacon_eval(rssi, max_rssi, freq): # 同時刻内で捕捉されたビーコンを評価．最大rssiと観測頻度による．20secも幅があるので
    return (max_rssi/rssi + freq) 

####### 観測モデル ###### # 各個人の各tiemstepに対して最もスコアの高いビーコンを決めるので出力はuserid, timestep, maxbeacon, absorption
def measuring_model(x):
    print(f'paramaterは{x}')
    qall = np.zeros(4)
    for file_name in file_list:
        if file_name.endswith('.csv'):
            base_name = file_name.split('.')[0]   
            userid = int(base_name)
                    
            file_path = os.path.join(search_folder, file_name)
            dfi = pd.read_csv(file_path) 
            nts = dfi['timestep'].nunique()                

            grouped = dfi.groupby('timestep')
            dfi_list = [group.reset_index(drop=True) for name, group in grouped]  
            qi = np.zeros(4)  # userid, timestep, maxbeacon, absorptionを後で入れる

            for t in range(nts):
                dfit = dfi_list[t]
                ts = int(dfit.loc[0, 'timestep'])

                count_tot = len(dfit) # 個人i時点tのcountの総和はdfitの長さそのもの
                        
                result_beacon = dfit.groupby('ID')
                result_beacon_list = [group.reset_index(drop=True) for name, group in result_beacon]

                # 各ビーコンのscoreを記録するためのdict
                dict = {}

                for j in range(len(result_beacon_list)): # 各ビーコンの結果を束ねたdataframe
                    dfitj = result_beacon_list[j]
                    count = len(dfitj) # そのビーコンでの検出回数
                    jid = dfitj.loc[0, 'ID']
                    rssi = dfitj['RSSI'].max() # そのビーコンでの最大観測強度

                    max_rssi = max_jt[jid-1, ts-1] # tsでのbeaconのmaxのrssi
                    freq = count / count_tot

                    # このビーコンのスコアを計算
                    jscore = beacon_eval(rssi, max_rssi, freq)

                    # dictにjidとjscoreを入れる
                    dict[jid] = jscore

                # dictに全部入っているので比較
                max_beacon = max(dict, key = dict.get) # score maxのビーコン

                # 個人i時刻tの結果（最もスコアの高かったビーコン）．absorptionの列はとりあえず0のまま残しておく
                qit = np.array([userid, ts, max_beacon, 0])
                qi = np.vstack((qi, qit))
            
            qi = np.delete(qi, 0, axis = 0)

            # ここまでで終了したので，qiの最後の行のmaxbeaconの値を取得しそれを最後の列に入れる
            abs = qi[-1, 2] # これで最後の行のmaxbeaconの列（0から数えて2列目）
            
            # qiの最後の列の値を全てabsにする
            qi[:, -1] = abs

            # 全個人に対してvstackしていってqallを作る
            qall = np.vstack((qall, qi))

    qall = np.delete(qall, 0, axis = 0)
    return qall 

###### 経路選択モデル ####### 
###### 初期設定 ######
V0 = np.full((L, D), -1) # exp(0)=1よりexp(-1)は小さくなるから?
z0 = np.exp(V0)

###### TSを設定しないといけない ###### #### 一斉に発生すると考えて良さそう→とりあえず時間構造化しないで解く
#TS = 10

V = V0
z = z0
beta = x0[0] # dRLなのでbeta推定．xの最後の要素をbetaとする
# beta = 0.9 # dRLなのでbeta推定．xの最後の要素をbetaとする

###### 効用関数 ######
def linkv(x): 
    vinst = np.exp(df_link['length']/10 * x[0]) #+ df_link_integrated['staire'] * x[1]) # + df_link_integrated['staire_with_esc'] * x[3])
    return vinst # 出力形式はseries

###### 即時効用行列 ######
def Mset(x): 
    cost = linkv(x)
    cost = pd.concat([cost]*L, axis=1)
    cost = cost.T
    cost_numpy = cost.values # DataFrameをNumPy配列に変換
    return cost_numpy

###### 価値関数 ###### # 時間構造化するなら変わってくるが，，，
def newV(x):
    V = np.zeros((L, D))
    z = np.exp(V)

    beta = x[-1]
    
    for d in range(D): 
        d_linkid = ddata[d]
        d_index = df_link[df_link['linkid'] == d_linkid].index 
        z[d_index, d] = 1                   # 目的地がdの時，dでの期待効用Vd(d)=0から
        M = np.zeros((L, L))
        B = np.zeros((L, 1))
        B[d_index, 0] = 1

        # Mをdごとに更新？
        for k in range(L): 
            for a in range(L): 
                Ika = I[k, a] 
                if Ika == 1:                # 接続してなければ無関係（0のまま）
                    if a == d_index: 
                        M[k, a] = 1         # 吸収リンクの即時効用はexp(0)=1
                    else:
                        M[k, a] = Mset(x)[k, a]
        dL = 100
        zd = z[:, d].reshape(L, 1) 

        # z求解
        count = 0
        while dL >= 0.01:
            zdd = zd.copy()
            # print(zdd)
            zd = M @ (zdd ** beta) + B 
            dL = np.sum(np.abs(zdd - zd)) 
            # dL = np.linalg.norm(zdd - zd, axis=0) 
            count += 1

        # z更新
        z[:, d] = zd[:, 0] 
        zd = np.where(zd == 0, 1, zd)  
        one_dim_array = np.log(zd).ravel()   # 1次元配列に
        V[:, d] = one_dim_array 

    return z

###### 対数尤度関数 ###### 
def loglikelihood(x):
    LL = 0

    beta = x[-1]

    # ここで観測モデルに入れる
    print(f'パラメタ{x}で観測モデルを回します')
    qall = measuring_model(x)

    condition = np.logical_or.reduce((qall[:, -1] == 16, qall[:, -1] == 20, qall[:, -1] == 21))

    # 条件に合致しない行のインデックスを取得します
    indices_to_keep = np.where(condition)[0]

    # 条件に合致しない行のみを抽出します
    filtered_qall = qall[indices_to_keep]

    # numpyのままではグルーピング不可なのでqallをdataframeにし，列カラムをつける
    mres = pd.DataFrame(filtered_qall, columns=['userid', 'timestep', 'maxbeacon', 'absorption']) # + [i for i in range(1, len(df_link_odds)*2+1)])

    # 観測結果をdで分割
    grouped = mres.groupby('absorption')
    df_list = [group for name, group in grouped]
    df_list = [data.reset_index(drop=True) for data in df_list]    

    # loglikelihood内で価値関数更新
    Z = newV(x) 
    print(Z)

    # 目的地dごとに計算
    for d in range(D):
        d_linkid = ddata[d] 
        d_index = df_link[df_link['linkid'] == d_linkid].index
        d_index = d_index.tolist()
        d_index = d_index[0] 

        # 価値関数
        z = Z[:, d].reshape(L, 1) # 価値関数は固定じゃなくてloglikelihood内で逐次更新→直したらループが終わらないことは無くなった
        z = z ** beta
        ZD = np.tile(z, (1, L))
        ZD = ZD.T

        # Mをdごとに更新（dループの外で問題はなさそう）
        M = np.zeros((L, L))
        for k in range(L): 
            for a in range(L): 
                Ika = I[k, a] 
                if Ika == 1:                            # 接続してなければ無関係（0のまま）
                    if a == d_index: 
                        M[k, a] = 1                     # 吸収リンクの即時効用はexp(0)=1（接続してたら）
                    else:
                        M[k, a] = Mset(x)[k, a]

        # 選択確率
        Mz = (M @ z != 0) * (M @ z) + (M @ z == 0)  
        MZ = np.tile(Mz, (1, L))  
        p = (M * ZD) / MZ

        print(p)

        df = df_list[d]

        grouped2 = df.groupby('userid')
        df_list2 = [group for name, group in grouped2] 
        df_list2 = [data2.reset_index(drop=True) for data2 in df_list2]
        count = 0

        for i in range(len(df_list2)):
            dfi = df_list2[i] # 各自の結果（userid, timestep, maxbeacon, absorption）
            userid = dfi.loc[0, 'userid']
            LLi = 0 
            at_cand_list = [] 

            # 各時刻ごとにmaxbeaconを参照．dfiの長さが滞在timestep数と同じになる
            for t in range(0, len(dfi)):                     
                max_beacon = int(dfi.loc[t, 'maxbeacon']) 
                ts = dfi.loc[t, 'timestep']

                at_1_list = at_cand_list 
                at_cand_list = [] 

                if t == 0: 
                    # 次のmaxbeacon 
                    next_max_beacon = int(dfi.loc[1, 'maxbeacon'])
                    # next_max_beaconの座標
                    x_nb = df_ble.loc[next_max_beacon-1, 'x']
                    y_nb = df_ble.loc[next_max_beacon-1, 'y']
                    z_nb = df_ble.loc[next_max_beacon-1, 'floor']
                    loc_nb = np.array([x_nb, y_nb, z_nb])

                    # 候補リンク max_beaconとの距離が最も近いリンクが候補になる→無向扱いなのでこれで一個に候補が絞られる
                    dist_list = d_array[:, max_beacon-1]
                    dist_min_link = np.argwhere(dist_list == np.min(dist_list)).flatten()+1 # 要素数一つのはず
                    
                    a0 = dist_min_link[0]
                    at_cand_list = [a0] 

                if t >= 1 and t <= (len(dfi)-2):            
                    for at_1 in at_1_list: # at_1に接続しているリンクを全部とる
                        a_row = I[at_1-1, :]
                        at_cand = np.where(a_row == 1)[0]+1 # np.whereを用いるidなので，+1をする．list
                        at_cand_list.extend(list(set(at_cand) - set(at_cand_list))) # 重複なし．これが全atの候補
                    
                    # 各候補リンクに対してp(j|k)(pmat)を算出（これが観測確率になる）．kの候補がいっぱいあるので，まず全てのkに対して処理を行う
                    for at in at_cand_list:
                        dist = d_array[at-1, max_beacon-1]                                     
                        min_dist = d_array[:, max_beacon-1].min() # max_beaconに一番近いリンクとの距離
                        pmat = mq(dist, min_dist) # これは観測方程式，max_beaconと距離が近いリンクほど観測確率が大きくなるという単純な理屈
                        
                        # ここでもっとat_1を絞る．at_1_listに入っていてかつatと接続する→atの列が1である行のindex
                        at_col = I[:, at-1]
                        at_connected = np.where(at_col == 1)[0]+1 # np.whereを用いるidなので，+1をする．これlistのはず
                        common_list = [link for link in at_1_list if link in at_connected] # つまり

                        for at_1 in common_list:
                            # print(f'今見てるんはuser{userid}時刻{ts}max_beacon{max_beacon}，{at_1}から{at}への遷移')
                            at_prime_list = []
                            nume = pmat * p[at_1-1, at-1]

                            # deno計算．at_1に接続しているリンクたち．
                            at_1_row = I[at_1-1, :]
                            at_prime_list = np.where(at_1_row == 1)[0]+1 

                            deno = 0
                            for at_prime in at_prime_list:
                                # print(f'今のat_primeは{at_prime}')
                                dist = d_array[at_prime-1, max_beacon-1] # リンクの中点の方がいいかな→多分ね # ここもmax_beaconに対して実施（時刻tに紐づいている）
                                pmat_prime = mq(dist, min_dist)
                                deno += pmat_prime * p[at_1-1, at_prime-1]
                            if deno == 0:
                                continue

                            delta = nume / deno 

                            pp = (p[at_1-1, at-1] == 0) + ((p[at_1-1, at-1] != 0) * p[at_1-1, at-1])
                            LLi += delta * np.log(pp) # p=1になることはない，接続するのが一つでも滞在するという選択肢もあるので（のはず）
                            # print(f'↑の時，デルタ{nume}/{deno}={delta}，選択確率{pp}')
                                
                if t == (len(dfi) - 1): # 最後の滞在リンクは確定
                    aT = None
                    if max_beacon == 16: # node39
                        aT = 25 # 49 # 93
                    if max_beacon == 20: # node28
                        aT = 17 # 33 # 91
                    if max_beacon == 21: # node29
                        aT = 18 # 35 # 92

                    if aT is not None:
                        dist = d_array[aT-1, max_beacon-1]
                        min_dist = d_array[:, max_beacon-1].min()
                        pmat = mq(dist, min_dist) 

                        for at_1 in at_1_list:
                            at_prime_list = []

                            nume = pmat * p[at_1-1, aT-1]
                            if nume == 0:
                                continue

                            at_1_row = I[at_1-1, :]
                            at_prime_list = np.where(at_1_row == 1)[0]+1

                            deno = 0
                            for at_prime in at_prime_list:
                                dist_prime = d_array[at_prime-1, max_beacon-1] 
                                pmat_prime = mq(dist_prime, min_dist) 
                                deno += pmat_prime * p[at_1-1, at_prime-1]

                            if deno == 0:
                                    continue
                            
                            delta = nume / deno 

                            pp = (p[at_1-1, aT-1] == 0) + ((p[at_1-1, aT-1] != 0) * p[at_1-1, aT-1])
                            LLi += delta * np.log(pp) # p=1になることはない，接続するのが一つでも滞在するという選択肢もあるので（のはず）
                            
                            # print(f'user{userid}時刻{ts}つまり最後のmaxビーコンのidは{max_beacon}，リンクは{aT}デルタは{nume}/{deno}で{delta}，pmatは{pmat}，経路選択確率は{pp}')   
            LL += LLi # 個人に対して和をとる
            count += 1

        print(f'パラメタ{x}のもとでLLが回り，計算したuserは{count}人でLL={LL}') # LLは負のはず
    
    return -LL

x1 = np.array((-100,1))
print(loglikelihood(x1))


start!
パラメタ[-100    1]で観測モデルを回します
paramaterは[-100    1]
[[0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [9.85967654e-305 9.85967654e-305 9.85967654e-305]
 [9.85967654e-305 9.85967654e-305 9.85967654e-305]
 [9.85967654e-305 9.85967654e-305 9.85967654e-305]
 [9.85967654e-305 9.85967654e-305 9.85967654e-305]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [7.12457641e-218 7.12457641e-218 7.12457641e-218]
 [2.66919022e-109 3.56228820e-217 3.56228820e-217]
 [2.66919022e-109 2.66919022e-109 4.98720348e-217]
 [1.00000000e+000 3.56228820e-217 3.56228820e-217]
 [2.84983056e-217 1.00000000e+000 2.84983056e-217]
 [0.00000000e+000 0.000000