In [1]:
import numpy as np

# サンプルデータ
od = 3
t = 2
pk = np.random.randint(1, 10, size=(od, t+2, od))  # 3次元配列の例
Pall = np.random.randint(1, 10, size=(od, t+1, od, od))  # 4次元配列の例

# pk[od, t, :] は行ベクトルとして取得されます
result = pk[od-1, t, :] @ Pall[od-1, t, :, :]

# 結果の表示

print("pk[od, t, :]:", pk[od-1, t, :])
print("Pall[od, t, :, :]:\n", Pall[od-1, t, :, :])
print("行列積の結果:", result)


pk[od, t, :]: [9 4 4]
Pall[od, t, :, :]:
 [[3 8 5]
 [8 3 3]
 [5 4 8]]
行列積の結果: [ 79 100  89]


In [3]:
import numpy as np

# TLmatrix[t-1, :, :] があると仮定
TLmatrix = np.array([[1, 0, 3], [0, 0, 5], [0, 0, 0]])  # 仮の行列

print(TLmatrix)

# 方法1: any() を使って非零の要素を持つ列を見つける
non_zero_columns = np.any(TLmatrix != 0, axis=0)
klist = np.where(non_zero_columns)[0]

# 方法2: nonzero() を使って非零の要素がある列のインデックスを取得する
non_zero_indices = np.nonzero(np.any(TLmatrix != 0, axis=0))[0]
klist = non_zero_indices.tolist()

# 結果を表示
print("非零の要素を持つ列のインデックス:", klist)


[[1 0 3]
 [0 0 5]
 [0 0 0]]
非零の要素を持つ列のインデックス: [0, 2]
