In [1]:
print('a')

a


In [2]:
import random
import numpy as np 

randarray = np.random.rand(2)

print(randarray)

random_array = np.random.uniform(low=-1, high=1, size=2)

print(random_array)


[0.06271769 0.77978731]
[ 0.22779854 -0.84125079]


In [1]:
print(int(89.2))

89


In [18]:
import pandas as pd
import numpy as np

# サンプルデータの作成（実際のデータに合わせて変更してください）
data = {'t': [0, 1, 2, 3, 0],
        'k': [1, 2, 1, 3, 2]}

df_res_all = pd.DataFrame(data)

# サンプルデータをNumPy配列に変換
res_all = df_res_all.to_numpy()

# インデックス操作のベクトル演算に変更
timesteps = res_all[:, 0].astype(int)
links = res_all[:, 1].astype(int)

vizu_all = np.zeros((max(timesteps) + 1, max(links) + 1), dtype=int) # 普通にvizu_all = np.zeros((T, L))と同じ
T = 4
L = 3
# vizu_all = np.zeros((T, L))
np.add.at(vizu_all, (timesteps, links), 1)

# vizu_allの結果を表示
print(vizu_all)


[[0 1 1 0]
 [0 0 1 0]
 [0 1 0 0]
 [0 0 0 1]]


In [16]:
vizu_allw = np.zeros((T, L))
for i in range(len(df_res_all)):
    t = int(df_res_all.loc[i, 't']) # df_res_allでのtが0~10で振っているのでtは0~10．なのでそのままindexとして使える
    k = int(df_res_all.loc[i, 'k']) # kはid，indexはk-1．
    vizu_allw[t, k-1] += 1 ## 1列目がtimestepなのでindexとlink id は同じ

print(vizu_allw)

[[1. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]


In [24]:
import pandas as pd 
import numpy as np 

df_ = pd.read_csv('/Users/takahiromatsunaga/res2023/results/assigned_20230130_1745_all.csv')


# サンプルデータをNumPy配列に変換
res_all = df_.to_numpy()

# インデックス操作のベクトル演算に変更
timesteps = res_all[:, 2].astype(int)
links = res_all[:, 3].astype(int)

vizu_all_ = np.zeros((max(timesteps) + 1, max(links) + 1), dtype=int) # 普通にvizu_all = np.zeros((T, L))と同じ
T = 4
L = 3
# vizu_all = np.zeros((T, L))
np.add.at(vizu_all_, (timesteps, links), 1)

# vizu_allの結果を表示
np.set_printoptions(threshold=np.inf)

print(vizu_all_)



[[   0  424  519  376  371   43   25  586    0  813   29  864  353   20
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0]
 [   0   48  373  311   85   40    2   40  437   90  564  125  475   58
     0    0    0    0    0    0    0    0    0    0    0    0  145    0
    76    0  303    0  248    0  168    0  173    0  409    0   21    0
   232    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0]
 [   0    8   73  265   42    8    2    6   71  325  134  213   98  117
     0    0    0    0    0    0    0    0    0    0    0    0   29  145
    38   76  254  303  159  248   39  168  181  173  223  409   12   21
   316  232   35    0    0    0    0    0    0  

In [25]:
columns_sum = np.sum(vizu_all_, axis = 0)
print(columns_sum)

[    0   484   991  1055   538   100    30   637   551  1369   965  1455
  1389   346  1135  1108   889  1503   958   289   525  1271   694   690
   886  1240   182   182   134   134   817   817   467   467   219   219
   444   444   931   931    46    46   981   981   204   204     0     0
     2     2     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0 34131 37363 24728 16387 16667]


In [27]:

import numpy as np

array_1d = np.full((8), 6)
print(array_1d)



[6 6 6 6 6 6 6 6]


In [32]:
import numpy as np

# 仮のデータ（実際のデータに合わせて変更してください）
A = np.random.random((7, 5))
b = np.random.random(7)
print(A)
print(b)
# ブロードキャストを使用してAとbの要素ごとの積を計算
A_b = A * b[:, np.newaxis] ## 要素ごとの計算はいつも通り*だが列ベクトルに変換してる
#A_bt = A * b.T
print(b[:, np.newaxis])
print(b.T)
# 結果を表示
print(A_b)
#print(A_bt)


[[0.9404781  0.72473906 0.54808209 0.56485128 0.4544549 ]
 [0.40495857 0.18000527 0.13820993 0.50499876 0.58056407]
 [0.15312232 0.57611244 0.73489161 0.93093467 0.07139541]
 [0.85280718 0.34288477 0.3527909  0.71057642 0.05900113]
 [0.78567009 0.65173573 0.87442429 0.55265558 0.00391317]
 [0.41672476 0.07583204 0.67233321 0.13748901 0.91572451]
 [0.81163117 0.43838447 0.46594374 0.00437462 0.13402444]]
[0.51928972 0.85624339 0.96656346 0.49767259 0.43994841 0.84113418
 0.34915314]
[[0.51928972]
 [0.85624339]
 [0.96656346]
 [0.49767259]
 [0.43994841]
 [0.84113418]
 [0.34915314]]
[0.51928972 0.85624339 0.96656346 0.49767259 0.43994841 0.84113418
 0.34915314]
[[0.48838061 0.37634954 0.28461339 0.29332146 0.23599376]
 [0.3467431  0.15412832 0.11834134 0.43240185 0.49710414]
 [0.14800244 0.55684923 0.71031937 0.89980743 0.06900819]
 [0.42441876 0.17064435 0.17557436 0.35363441 0.02936324]
 [0.34565431 0.2867301  0.38470157 0.24313994 0.00172159]
 [0.35052144 0.06378492 0.56552244 0.1156467

In [33]:
import numpy as np
N = 7
M = 5
# 仮のデータ（実際のデータに合わせて変更してください）
array = np.random.random((N, M))

# 配列の形状取得
shape = array.shape

# 配列の全要素数取得
total_elements = array.size

# 結果を表示
print("Shape:", shape)
print("Total elements:", total_elements)


Shape: (7, 5)
Total elements: 35


In [35]:
31+61+37+67+78+79

353

In [36]:
480-353

127